### ISSUE TITLE
Use common project structure

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/SamyilovEvgeniiTestingProject#1]
В java проектах принято файлы исходного кода организовать в определнной структуре папок. Описание одного из наиболее распространенных способов организации проекта смотри [здесь](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) или [здесь](https://stackoverflow.com/questions/41638654/java-project-folder-structure-in-intellij-idea). 

Кроме того, в java принято орагнизовывать классы в пакеты. Общепринятые правила именования пакетов см. [здесь](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Понятно, что у Вас скорее всего нет никакого сайта. В этом случае можно его придумать или взять название орагнизации, в рамках которой делается проект. Например, `org.spbstu.your_surname`.

Каждый файл исходного кода должен находится в структуре папок, соответствующей названию его пакета. Например, если файл исходного кода озаглавлен директивой `package com.mycompany.myname`, то этот файл должен располагаться по пути `com/mycompany/myname` относительно папки с исходным кодом внутри проекта.

**Comment by Eugehabatikov** [comment]
структура сделана

**Comment by JohnKhandygo** [comment]
Читай внимательно ссылки, которые я скинул. Структура папок не соответствует общепринятой. В имени пакетов не принято использовать camelCase, вместо этого используют `_` как разделитель между словами, либо обходятся вовсе без него (то есть просто все слова в нижнем регистре без разделителей). В Вашем случае можно использовать просто фамилию в последней части названия пакета.

**Comment by Eugehabatikov** [comment]
раскидал по разным папкам,надеюсь,надо было так

**Comment by JohnKhandygo** [comment]
Что толку надеяться? Надо просто **внимательно** прочитать, что написано в ссылках.

В первой ссылке есть табличка: левая колонка --- путь относительно корня проекта, правая --- что хранится в папке по этому пути. Давайте так: Вы берете и в комментарии к этому issue пишите табличку из трех колонок:
1. Тип файлов. В этой колонке значения из правой колонки по ссылке. Например, Application/Library sources.
2. Путь, по которому **должен** хранится данный тип файлов. Здесь соответствующие значения из левой колонки по ссылке.
3. Путь, по которому хранится данный вид файлов в Вашем проекте. Структура пакетов при этом не учитывается. 
Если какой-то тип файлов отсутствует в Вашем проекте, то эту строчку можно не рассматривать вовсе.

**Comment by Eugehabatikov** [comment]
Application/Library   sources src/main/java    SamyilovEvgeniiTestingProject/src
Test sources              src/test/java                   SamyilovEvgeniiTestingProject/PolynomTest
Project's readme       README.txt                    SamyilovEvgeniiTestingProject/README.txt
Resource filter files   src/main/filters               SamyilovEvgeniiTestingProject/

**Comment by JohnKhandygo** [comment]
Про две последние строчки можете забыть, наиболее интересны, конечно, файлы исходного кода и тестовые файлы. Корень проекта надо игнорировать. И речь идет не о том, в каком классе написаны написаны тесты, а в какой директории они располагаются. Таким образом, получаем:
- **App sources** || src/main/java || src
- **Test sources** || src/test/java || src
Значения во второй и третей колонках не совпадают. А должны.
