### ISSUE TITLE
Add properly configured .gitignore file

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/SamyilovEvgeniiTestingProject#3]
В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).

**Comment by JohnKhandygo** [comment]
После добавления .gitignore Вам надо будет также удалить все игнорируемые файлы из удаленного репозитория. Подробную инструкцию смотри [здесь](https://gist.github.com/scy/6636390).

**Comment by Eugehabatikov** [comment]
я удалил файл из проекта,но он там все еще висит 
это я что то не правильно делаю?

**Comment by Eugehabatikov** [comment]
просто скажите мне,я хотя бы сам его правильно написал?как удалить я не понял(

**Comment by JohnKhandygo** [comment]
Нет, .gitignore у Вас сформирован неправильно. То есть корректно с точки зрения синтаксиса, но в нем не игнорируются project specific файлы.

**Comment by Eugehabatikov** [comment]
теперь игнорирую эти файлы
вроде

**Comment by Eugehabatikov** [comment]
файлы формата *.iml дописал
