### ISSUE TITLE
Use consistent code style/formatting

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/SamyilovEvgeniiTestingProject#4]
В исходном коде программы встречаются разночтения стиля кодирования/форматирования. В качестве референсного стиля кодирования можно использовать [google java style guide](https://google.github.io/styleguide/javaguide.html). 

Также в исходном коде крайне нежелательно наличие комментариев, которые не являются Javadoc'ом. Если Ваш код нельзя понять без комментариев, значит это плохой код.

Кроме  того, в своем коде следует по возможности избегать комментариев, отличных от javadoc. Если Вам нужны комментарии для того, чтобы Ваш код был понятен, то это плохой код.

**Comment by Eugehabatikov** [comment]
комментарии убраны

**Comment by JohnKhandygo** [comment]
У Вас название одного из методов с большой буквы. В java все, кроме классов и статических переменных принято именовать в [lowerCamelCase](http://wiki.c2.com/?LowerCamelCase).

**Comment by Eugehabatikov** [comment]
поправил
