### ISSUE TITLE
Extend javadoc

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/SamyilovEvgeniiTestingProject#5]
Javadoc принято писать на английском языке. Кроме того, у Вас отсутствует javadoc для конструктора, а без него не совсем понятно, какой формат входной строки Вы допускаете. Также было бы неплохо для каждого метода добавить, что Вы возвращаете.

**Comment by Eugehabatikov** [comment]
поправлено

**Comment by JohnKhandygo** [comment]
Допустимый формат входной строки для конструктора описан недостаточно точно. Например, нигде не указано, что вокруг знаков между слагаемыми не допускается пробелов.

**Comment by Eugehabatikov** [comment]
джава док написан ,надеюсь,это то ,что Вы имели ввиду
