### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/SamyilovEvgeniiTestingProject#6]
- [x] По условию задачи Вам необходимо было реализовать метод рассчета значения при заданном (целом) `x`. Я у Вас этого метода не вижу.  
- [x] Функции `divide` и `modulo` реализованы некорректно. Остаток от деления двух полиномов не обязательно является числом. И вообще там сплошной копипаст между этими двумя функциями и бардак.

**Comment by Eugehabatikov** [comment]
поправлено(для расчета тестов нет,но функция точно верна,тесты кину утром)

**Comment by JohnKhandygo** [comment]
- [x] Полином легко может быть чем-то вроде `x^100`. При подсчете значения такого полинома в точке 100 произойдет переполнение `int`.  
- [x] Метод `divide` все еще реализован некорректно. С основной логикой деления в столбик все вроде бы окей, но вот про некоторые краевые случаи Вы подзабыли.
- [x] Метод `subtract` тоже реализован некорректно. 
- [x] А нельзя `LOOK_AROUND` сразу записать, без `format` внутри конструктора?
- [x] В классе `Polynom` есть неиспользуемые методы.
- [x] Вместо того, чтобы писать `dividend.coefficients.get(dividend.coefficients.firstKey())` лучше использовать `dividend.coefficients.firstEntry().getValue()`.
- [x] IDE некоторые вещи в Вашем коде подсвечивает желтеньким. Как правило, это значит, что Вы делаете что-то не так. Наведите курсор на подсвеченное выражение, прочитайте сообщения. Во многих случаях, если поставить курсов в середину подсвеченного выражения и нажать ctrl + Enter, idea предложит автоматическое исправление.

**Comment by Eugehabatikov** [comment]
поправлено все ,кроме метода деления ,с ним я пока не понял в чем проблема

**Comment by JohnKhandygo** [comment]
Окей. Но Вы должны понимать, что `long` тоже может переполниться.

Все, что не отмечено галочками из предыдущего комментария, актуально.

Под краевыми случаями в `divide` я имел ввиду деление нуля на что угодно и деление чего угодно на ноль. Оба случая должны быть зафиксированы в тестах.

**Comment by Eugehabatikov** [comment]
все сделано

**Comment by JohnKhandygo** [comment]
Для удобства отметил галочками все предыдущие замечания. Осталась одна проблема: Вы, видмо, считаете, что полином равен нулю, когда его значение в единице равно нулю, но это не правда. В результате текущая реализация будет бросать исключение при делении на полином `x - 1`. И сообщения к исключениям тоже принято писать на английском языке.
