### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/SamyilovEvgeniiTestingProject#7]
- [ ] Обычно метод `toString` не тестируют. Это просто обязательный метод, но его, как правило используют только для удобства отладки. То есть он должен выводить что-то осмысленное, но тестировать его совсем не обязательно.
- [ ] Все Ваши тесты основаны на проверке строкового представления `Polynom`. Это не очень удобно, поскольку если Вам понадобится изменить строковое представление `Polynom`, Ваши тесты сразу же резко сломаются.

**Comment by Eugehabatikov** [comment]
поправлено
