### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/SamyilovEvgeniiTestingProject#8]
Поскольку Вам осталось исправить совсем чуть-чуть до завершения первого задания, выдаю следующее.

Его проверку начинаю только после исправления всех замечаний к предыдущему заданию, однако начинать выполнять это задание Вы можете хоть сейчас.

**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**uniq**
Объединение последовательностей одинаковых идущих подряд строк в файле в одну:
file задаёт имя входного файла. Если параметр отсутствует, следует считывать текст с консоли.
Флаг -o ofile  задаёт имя выходного файла. Если параметр отсутствует, следует выводить результаты на консоль.
Флаг -i означает, что при сравнении строк следует не учитывать регистр символов.
Флаг -s N означает, что при сравнении строк следует игнорировать первые N символов каждой строки. Выводить нужно первую строку.
Флаг -u означает, что следует выводить в качестве результата только уникальные строки.
Флаг -с означает, что перед каждой строкой вывода следует вывести количество строк, которые были заменены данной (т.е. если во входных данных было 2 одинаковые строки, в выходных данных должна быть одна с префиксом “2”).

Command line: uniq [-i] [-u] [-c] [-s num] [-o ofile] [file]

В случае, когда какое-нибудь из имён файлов указано неверно, следует выдать ошибку.

Кроме самой программы, следует написать автоматические тесты к ней, а также скрипты сборки/запуска программы (для проверки работоспособности в реальных условиях, из консоли).

Если задание будет выполняться в другом репозитории, напишите об этом в комментарии.

**Comment by Eugehabatikov** [comment]
вопрос
это очепятка?"Флаг -s N означает, что при сравнении строк следует игнорировать первые N символов каждой строки. Выводить нужно первую строку."

**Comment by JohnKhandygo** [comment]
Нет, это не опечатка.

**Comment by Eugehabatikov** [comment]
тогда обьясните , пожалуйста , как это

**Comment by Eugehabatikov** [comment]
примером , если можно

**Comment by JohnKhandygo** [comment]
Пусть есть две строки `s1` и `s2`, и при запуске программы был указан флаг `-s` со значением `N`. Тогда, если строки `s1` и `s2` равны с точностью до первых `N` символов (то есть равны после отбросфывния первых `N` символов), то эти строки считаются неуникальными и программа должна вывести первую из них (ту, что раньше встречалась в тексте). 

Пример, пусть во входном файле содержатся следующие строки:
```
...
abcdefghi
jklmefghi
...
```
Тогда при запуске программы с параметром `-s 4` эти две строки считаются уникальными (~~abcd~~efghi == ~~jklm~~efghi) и при их "склеивании" остается только первая строка (abcdefghi).

**Comment by Eugehabatikov** [comment]
а можно я на "3" соглашусь , а вы мне мелкие косяки в первом задании простите?（я еще сецчас добавлю гитигнор поправленный）

**Comment by Eugehabatikov** [comment]
а можно я на "3" соглашусь , а вы мне мелкие косяки в первом задании простите?（я еще сецчас добавлю гитигнор поправленный）

**Comment by Eugehabatikov** [comment]
я так в принципе то

**Comment by Eugehabatikov** [comment]
я так в принципе знаю , как поправить impl но нет времени все , а дедлайн близко

**Comment by JohnKhandygo** [comment]
Так. Без паники. Для того, чтобы успешно получить аттестацию достаточно черновика второго задания. Закрывайте замечание про реализацию (Вам там два условия в if внутри divide исправить, особенно просто, раз Вы понимаете, как исправить), получите 4 за первое.

**Comment by Eugehabatikov** [comment]
поправлено,добавлены тесты на нуль

**Comment by JohnKhandygo** [comment]
Окей. Все другие issue закрыл, 4 за первое задание.

**Comment by JohnKhandygo** [comment]
Напишите, когда второе задание будет готово к проверке. Не забудьте скинуть в комментарий адрес репозитория, если он изменится.

**Comment by Eugehabatikov** [comment]
https://github.com/Eugehabatikov/Evgeniy_Samyilov_testing_progect_task2 
в общем,я потом пойму,как в один запилить,и сделаю,здесь поменять библиотеку и методы сделать еще пару
ну и ассерты
короче к пятнице будет готово(ну утро субботы крайний срок)

**Comment by Eugehabatikov** [comment]
Добрый день, Евгений.
Есть вопрос про опцию "-u".
1) Должны ли мы при наличии опции "-s" определять уникальность, отбрасывая первые N символов или не отбрасывая (учитывать опцию "s" только при слиянии)?
С уважением 
Евгений Самуйлов

**Comment by JohnKhandygo** [comment]
Если указаны и опция `-u`, и опция `-s`, то уникальность строк определяется с учетом значения в `-s`.

**Comment by JohnKhandygo** [comment]
Ну Вы помните, что без тестов, проверка не начинается. Сейчас у Вас там каша и Вы, наверное, не сделали, все что хотели, поэтому тем более не вижу смысла выкатывать замечания сейчас. Напишите, когда можно будет предметно смотреть второе задание.

**Comment by Eugehabatikov** [comment]
готово почти 
https://github.com/Eugehabatikov/Eugenii_Samyilov_testing_project_task2/tree/master

**Comment by Eugehabatikov** [comment]
допиливание напильником тестов

**Comment by Eugehabatikov** [comment]
сегодня я докручу тесты （чисто для красоты ＋дописать чутка）так что можете выкатывать замечания по коду

**Comment by JohnKhandygo** [comment]
Перенес описания задания в новый репозиторий, все замечания будут поялвться там.
